export const LISTAR_PAISES="LISTAR_PAISES";

export const FILTRAR_PAISES="FILTRAR_PAISES";
export const FILTRAR_PAISES_EXITO="FILTRAR_PAISES_EXITO";

export const BUSCAR_PAISES="BUSCAR_PAISES";

export const VER_PAIS="VER_PAIS";